Traceback (most recent call last):
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# relative humidity within chamber (%)
rh_chamber = 15
# arrhenius activation energy (kj/mol)
Ea = 40

rh_surface = pvdeg.humidity.rh_surface_outside(rh_ambient=WEATHER['relative_humidity'],
                                               temp_ambient=WEATHER['temp_air'],
                                               temp_module=temp_module)

arrhenius_deg = pvdeg.degradation.arrhenius_deg(weather_df=WEATHER, meta=META,
                                                rh_outdoor=rh_surface,
                                                I_chamber=I_chamber,
                                                rh_chamber=rh_chamber,
                                                temp_chamber=temp_chamber,
                                                poa=poa_df,
                                                temp_cell=temp_cell,
                                                Ea=Ea)

irr_weighted_avg_a = pvdeg.degradation.IwaArrhenius(weather_df=WEATHER, meta=META,
                                                    poa=poa_df, 
                                                    rh_outdoor=WEATHER['relative_humidity'],
                                                    temp_cell=temp_cell,
                                                    Ea=Ea)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[5], line 6[0m
[0;32m      3[0m [38;5;66;03m# arrhenius activation energy (kj/mol)[39;00m
[0;32m      4[0m Ea [38;5;241m=[39m [38;5;241m40[39m
[1;32m----> 6[0m rh_surface [38;5;241m=[39m [43mpvdeg[49m[38;5;241;43m.[39;49m[43mhumidity[49m[38;5;241;43m.[39;49m[43mrh_surface_outside[49m(rh_ambient[38;5;241m=[39mWEATHER[[38;5;124m'[39m[38;5;124mrelative_humidity[39m[38;5;124m'[39m],
[0;32m      7[0m                                                temp_ambient[38;5;241m=[39mWEATHER[[38;5;124m'[39m[38;5;124mtemp_air[39m[38;5;124m'[39m],
[0;32m      8[0m                                                temp_module[38;5;241m=[39mtemp_module)
[0;32m     10[0m arrhenius_deg [38;5;241m=[39m pvdeg[38;5;241m.[39mdegradation[38;5;241m.[39marrhenius_deg(weather_df[38;5;241m=[39mWEATHER, meta[38;5;241m=[39mMETA,
[0;32m     11[0m                                                 rh_outdoor[38;5;241m=[39mrh_surface,
[0;32m     12[0m                                                 I_chamber[38;5;241m=[39mI_chamber,
[1;32m   (...)[0m
[0;32m     16[0m                                                 temp_cell[38;5;241m=[39mtemp_cell,
[0;32m     17[0m                                                 Ea[38;5;241m=[39mEa)
[0;32m     19[0m irr_weighted_avg_a [38;5;241m=[39m pvdeg[38;5;241m.[39mdegradation[38;5;241m.[39mIwaArrhenius(weather_df[38;5;241m=[39mWEATHER, meta[38;5;241m=[39mMETA,
[0;32m     20[0m                                                     poa[38;5;241m=[39mpoa_df, 
[0;32m     21[0m                                                     rh_outdoor[38;5;241m=[39mWEATHER[[38;5;124m'[39m[38;5;124mrelative_humidity[39m[38;5;124m'[39m],
[0;32m     22[0m                                                     temp_cell[38;5;241m=[39mtemp_cell,
[0;32m     23[0m                                                     Ea[38;5;241m=[39mEa)

[1;31mAttributeError[0m: module 'pvdeg.humidity' has no attribute 'rh_surface_outside'

